/* apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: ClusterIP
  selector:
    app: nodejs
  ports:
  - port: 80
    targetPort: 3000 */


version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'

    
